package vendeur;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

public class VendeurController {
	@FXML
	private Label exit;
	@FXML
    private void handleButtonAction(MouseEvent event) {
       System.exit(0);
	}
	
       
		@FXML
		public void signout(MouseEvent event) throws IOException {
			// TODO Autogenerated
			Parent homePage = FXMLLoader.load(getClass().getResource("/application/Login.fxml"));
	        Scene homepageScene = new Scene(homePage);
	        Stage appStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        appStage.setScene(homepageScene);
	        homepageScene.setFill(Color.TRANSPARENT);
	        appStage.show();
		
	}
	@FXML
    private void categorie(ActionEvent event) throws IOException {
       
		   Stage stage1 = new Stage();


        Scene scene = new Scene(FXMLLoader.load(getClass().getResource("/com_categorie/Categorie.fxml")));
        stage1.setScene(scene);
        stage1.initStyle(StageStyle.TRANSPARENT);
        scene.setFill(Color.TRANSPARENT);
        stage1.show();
        
	}
	@FXML
    private void article(ActionEvent event) throws IOException {
		   Stage stage1 = new Stage();

            

            Scene scene = new Scene(FXMLLoader.load(getClass().getResource("/com_article/Article.fxml")));
            stage1.setScene(scene);
            stage1.initStyle(StageStyle.TRANSPARENT);
            scene.setFill(Color.TRANSPARENT);
            stage1.show();
	}

@FXML
private void clients(ActionEvent event) throws IOException {
   
	   Stage stage1 = new Stage();

        

        Scene scene = new Scene(FXMLLoader.load(getClass().getResource("/com_client/Client.fxml")));
        stage1.setScene(scene);
        stage1.initStyle(StageStyle.TRANSPARENT);
        scene.setFill(Color.TRANSPARENT);
        stage1.show();
}

@FXML
private void commandes(ActionEvent event) throws IOException {
   
	   Stage stage1 = new Stage();

        

        Scene scene = new Scene(FXMLLoader.load(getClass().getResource("/com_commande/Commande.fxml")));
        stage1.setScene(scene);
        stage1.initStyle(StageStyle.TRANSPARENT);
        scene.setFill(Color.TRANSPARENT);
        stage1.show();
}
@FXML
private void factures(ActionEvent event) throws IOException {
   
	 Stage stage1 = new Stage();

        Scene scene = new Scene(FXMLLoader.load(getClass().getResource("/com_factures/Factures.fxml")));
        stage1.setScene(scene);
        stage1.initStyle(StageStyle.TRANSPARENT);
        scene.setFill(Color.TRANSPARENT);
        stage1.show();
}
@FXML
private void fournisseur(ActionEvent event) throws IOException {
   
	 Stage stage1 = new Stage();

        Scene scene = new Scene(FXMLLoader.load(getClass().getResource("/com_fournisseur/Fournisseur.fxml")));
        stage1.setScene(scene);
        stage1.initStyle(StageStyle.TRANSPARENT);
        scene.setFill(Color.TRANSPARENT);
        stage1.show();
}
}
