package com_commande;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import com_article.ArticleController;
import com_client.ClientController;
import com_connection.ConnectionDB;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import projet.bin.Article;

import projet.bin.Client;
import projet.bin.Commande;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class CommandeController implements Initializable{
	@FXML
	private Label lbl;
	@FXML
	private TextField quanttarticle;
	@FXML
	private TextField idclient;
	@FXML
	private TextField nomclient;
	@FXML
	private TextField prenomclient;
	@FXML
	private TextField telephoneclient;
	@FXML
	private TextField idarticle;
	@FXML
	private TextField refarticle;
	@FXML
	private TextField prixarticle;
	@FXML
	private TextArea details;
	@FXML
	private TableView <Commande>tabcom;
	@FXML
	private TableColumn <Commande,String>quantt;
	@FXML
	private TableColumn <Commande,String>idcomm;
	@FXML
	private TableColumn <Commande,String>idclien;
	@FXML
	private TableColumn <Commande,String>idarticl;
	@FXML
	private TableColumn <Commande,String>date;
	@FXML
	private TableColumn <Commande,String>Nom;
	@FXML
	private TableColumn <Commande,String>prenom;
	@FXML
	private TableColumn <Commande,String>tel;
	@FXML
	private TableColumn <Commande,String>reference;
	@FXML
	private TableColumn <Commande,String>prix;
	@FXML
	private TableColumn <Commande,String>detail;
	@FXML
	private TextField rechercher;
	@FXML
	private Label exit;
	@FXML
	private TableView <Client>tabcli;
	@FXML
	private TableColumn <Client,String>idcli;
	@FXML
	private TableColumn <Client,String>nomcli;
	@FXML
	private TableColumn <Client,String>prencli;
	@FXML
	private TableColumn <Client,String>adrcli;
	@FXML
	private TableColumn <Client,String>telcli;
	@FXML
	private TableColumn <Client,String>email;
	@FXML
	private TableView <Article>tabart;
	@FXML
	private TableColumn <Article,String>idart;
	@FXML
	private TableColumn <Article,String>catart;
	@FXML
	private TableColumn <Article,String>qutt;
	@FXML
	private TableColumn <Article,String>pri;
	@FXML
	private TableColumn <Article,String>ref;
	@FXML
	private TableColumn <Article,String>desc;
	@FXML
	private TextField rechCli;
	@FXML
	private TextField RechArt;
	public ObservableList<Client> dataCli = FXCollections.observableArrayList();
	public ObservableList<Commande> dataCom = FXCollections.observableArrayList();
	public ObservableList<Article> dataArt = FXCollections.observableArrayList();
	// Event Listener on FontAwesomeIcon.onMouseClicked

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		viewCli();
		viewCom();
		viewArt();
		TableToTextCli();
		TableToTextCom();
		TableToTextArt();
		searchCli();
		searchCom();
		searchArt();
	}
	public void viewCli() {
		// TODO Autogenerated
		
		try {
			
    		Connection conn = ConnectionDB.conDB();
    		String sql = "SELECT * FROM `client`" ;
    		PreparedStatement stm  = conn.prepareStatement(sql);
    		ResultSet rs = stm.executeQuery();
    		tabcli.getItems().removeAll(dataCli);
    		while (rs.next())
    		{
    			dataCli.add(new Client(rs.getString(1) , rs.getString(2) , rs.getString(3) , rs.getString(4) , rs.getString(5) ,  rs.getString(6) ) );
    			
    		}
    		conn.close();
    		
		} catch (Exception e) {
			// TODO: handle exception
		}
    	
		idcli.setCellValueFactory(new PropertyValueFactory<Client, String>("id_client"));
    	nomcli.setCellValueFactory(new PropertyValueFactory<Client, String>("nom"));
    	prencli.setCellValueFactory(new PropertyValueFactory<Client, String>("prenom"));
    	adrcli.setCellValueFactory(new PropertyValueFactory<Client, String>("adresse"));
    	telcli.setCellValueFactory(new PropertyValueFactory<Client, String>("telephone"));
    	email.setCellValueFactory(new PropertyValueFactory<Client, String>("email"));
    	
    	tabcli.setItems(dataCli);	
	}
    
	
	public void viewArt() {
		// TODO Autogenerated
		
		try {
			
    		Connection conn = ConnectionDB.conDB();
    		String sql = "SELECT * FROM `article`" ;
    		PreparedStatement stm  = conn.prepareStatement(sql);
    		ResultSet rs = stm.executeQuery();
    		tabart.getItems().removeAll(dataArt);
    		while (rs.next())
    		{
    			dataArt.add(new Article(rs.getString(1) , rs.getString(2) , rs.getString(3) , rs.getString(4) , rs.getInt(5) ,  rs.getString(6), rs.getString(7) ,  rs.getString(8) ) );
    			
    		}
    		conn.close();
    		
		} catch (Exception e) {
			// TODO: handle exception
		}
    	
		idart.setCellValueFactory(new PropertyValueFactory<Article, String>("id"));
    	catart.setCellValueFactory(new PropertyValueFactory<Article, String>("nomcat"));
    	qutt.setCellValueFactory(new PropertyValueFactory<Article, String>("quantite"));
    	pri.setCellValueFactory(new PropertyValueFactory<Article, String>("prix"));
    	ref.setCellValueFactory(new PropertyValueFactory<Article, String>("ref"));
    	desc.setCellValueFactory(new PropertyValueFactory<Article, String>("desc"));
    	
    	tabart.setItems(dataArt);	
    	
	}
	
	public void viewCom() {
		// TODO Autogenerated
		
		try {
			
    		Connection conn = ConnectionDB.conDB();
    		String sql = "SELECT * FROM `commande`" ;
    		PreparedStatement stm  = conn.prepareStatement(sql);
    		ResultSet rs = stm.executeQuery();
    		tabcom.getItems().removeAll(dataCom);
    		while (rs.next())
    		{
    			dataCom.add(new Commande(rs.getString(1) , rs.getString(2) , rs.getString(3) , rs.getString(4) , rs.getString(5) ,  rs.getString(6), rs.getString(7) ,  rs.getString(8), rs.getString(9) ,  rs.getInt(10),  rs.getString(11) ) );
    			
    		}
    		conn.close();
    		
		} catch (Exception e) {
			// TODO: handle exception
		}
    	
		idcomm.setCellValueFactory(new PropertyValueFactory<Commande, String>("id"));
    	idclien.setCellValueFactory(new PropertyValueFactory<Commande, String>("idcli"));
    	idarticl.setCellValueFactory(new PropertyValueFactory<Commande, String>("idarticle"));
    	date.setCellValueFactory(new PropertyValueFactory<Commande, String>("datecom"));
    	Nom.setCellValueFactory(new PropertyValueFactory<Commande, String>("nomcli"));
    	prenom.setCellValueFactory(new PropertyValueFactory<Commande, String>("prenomcli"));
    	tel.setCellValueFactory(new PropertyValueFactory<Commande, String>("telcli"));
    	reference.setCellValueFactory(new PropertyValueFactory<Commande, String>("refarticle"));
    	prix.setCellValueFactory(new PropertyValueFactory<Commande, String>("prix"));
    	detail.setCellValueFactory(new PropertyValueFactory<Commande, String>("details"));
    	quantt.setCellValueFactory(new PropertyValueFactory<Commande, String>("quantite"));
    	
    	tabcom.setItems(dataCom);	
    	
	}
	
	@FXML
	public void back(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent homePage = FXMLLoader.load(getClass().getResource("/vendeur/Vendeur.fxml"));
	    Scene homepageScene = new Scene(homePage);
	    Stage appStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	    appStage.setScene(homepageScene);
	    homepageScene.setFill(Color.TRANSPARENT);
	    appStage.show();
	}
	@FXML
    private void handleButtonAction(MouseEvent event) {
       
            System.exit(0);
        }
	 public void vider (MouseEvent event)
	    {
	    	try {
	    		
	    		idclient.clear();
	    		nomclient.clear();
	    		prenomclient.clear();
	    		telephoneclient.clear();
	    		idarticle.clear();
	    		refarticle.clear();
	    		prixarticle.clear();
	    		details.clear();
	    		quanttarticle.clear();

			} catch (Exception e) {
				// TODO: handle exception
				System.out.println(e.getMessage());
			}
	    	
	    	
	    	
	    }
	  private void TableToTextCli() {
			tabcli.setOnMouseClicked(new EventHandler<MouseEvent>() {

				@Override
				public void handle(MouseEvent event) {
					// TODO Auto-generated method stub
					Client l =tabcli.getItems().get(tabcli.getSelectionModel().getSelectedIndex());
					idclient.setText(l.getId_client());
					nomclient.setText(l.getNom());
					prenomclient.setText(l.getPrenom());
					telephoneclient.setText(l.getTelephone());
					
				
				}
				
				
			});
		}
	  private void TableToTextArt() {
			tabart.setOnMouseClicked(new EventHandler<MouseEvent>() {

				@Override
				public void handle(MouseEvent event) {
					// TODO Auto-generated method stub
					Article l =tabart.getItems().get(tabart.getSelectionModel().getSelectedIndex());
					idarticle.setText(l.getId());
					refarticle.setText(l.getNomcat());
					prixarticle.setText(l.getPrix());
					String QUTT = Integer.toString(l.getQuantite());
					quanttarticle.setText(QUTT);
				
					
				
				}
				
				
			});
		}
	  private void TableToTextCom() {
			tabcom.setOnMouseClicked(new EventHandler<MouseEvent>() {

				@Override
				public void handle(MouseEvent event) {
					// TODO Auto-generated method stub
					Commande c =tabcom.getItems().get(tabcom.getSelectionModel().getSelectedIndex());
					idarticle.setText(c.getIdarticle());
					refarticle.setText(c.getRefarticle());
					prixarticle.setText(c.getPrix());
					idclient.setText(c.getIdcli());
					nomclient.setText(c.getNomcli());
					prenomclient.setText(c.getPrenomcli());
					telephoneclient.setText(c.getTelcli());
					details.setText(c.getDetails());
					String QUTT = Integer.toString(c.getQuantite());
					quanttarticle.setText(QUTT);
				
				}
				
				
			});
		}
	  private void loadDataDBCli() {
			dataCli.clear();
			try {
				Connection conn = ConnectionDB.conDB();
				PreparedStatement pst=conn.prepareStatement("Select * from client");
				ResultSet rs=pst.executeQuery();
				while(rs.next()) {
					dataCli.add(new Client(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)));
				}
			}
			catch(SQLException ex){
				Logger.getLogger(ClientController.class.getName()).log(Level.SEVERE, null,ex);
			}
			tabcli.setItems(dataCli);
		}
		    
		private void searchCli() {
			rechCli.setOnKeyReleased(e->{
				if(rechCli.getText().equals("")) {
					loadDataDBCli();
				}
				else {
					dataCli.clear();
					String sql= "Select * from client where id_client LIKE '%"+rechCli.getText()+"%' " + "UNION Select * from client where nom LIKE '%"+rechCli.getText()+"%' "+ "UNION Select * from client where prenom LIKE '%"+rechCli.getText()+"%' "+ "UNION Select * from client where adresse LIKE '%"+rechCli.getText()+"%' "+ "UNION Select * from client where email LIKE '%"+rechCli.getText()+"%' ";
					try {
						Connection conn = ConnectionDB.conDB();
						PreparedStatement pst=conn.prepareStatement(sql);
						ResultSet rs=pst.executeQuery();
						while(rs.next()) {
							dataCli.add(new Client(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)));
						}
						tabcli.setItems(dataCli);
					}catch(SQLException ex) {
						Logger.getLogger(ClientController.class.getName()).log(Level.SEVERE, null,ex);
					}
				}
						
			}
			);
		}
		
		private void loadDataDBArt() {
			dataCli.clear();
			try {
				Connection conn = ConnectionDB.conDB();
				PreparedStatement pst=conn.prepareStatement("Select * from article");
				ResultSet rs=pst.executeQuery();
				while(rs.next()) {
					dataArt.add(new Article(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getString(6),rs.getString(7),rs.getString(8)));
				}
			}
			catch(SQLException ex){
				Logger.getLogger(ArticleController.class.getName()).log(Level.SEVERE, null,ex);
			}
			tabart.setItems(dataArt);
		}
		    
		private void searchArt() {
			RechArt.setOnKeyReleased(e->{
				if(RechArt.getText().equals("")) {
					loadDataDBArt();
				}
				else {
					dataArt.clear();
					String sql= "Select * from article where Id_Article LIKE '%"+RechArt.getText()+"%' " + "UNION Select * from article where Nom_Cat LIKE '%"+RechArt.getText()+"%' "+ "UNION Select * from aticle where Nom_Fournisseur LIKE '%"+RechArt.getText()+"%' "+ "UNION Select * from article where Reference LIKE '%"+RechArt.getText()+"%' "+ "UNION Select * from article where Description\r\n" + 
							" LIKE '%"+RechArt.getText()+"%' ";
					try {
						Connection conn = ConnectionDB.conDB();
						PreparedStatement pst=conn.prepareStatement(sql);
						ResultSet rs=pst.executeQuery();
						while(rs.next()) {
							dataArt.add(new Article(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getString(6),rs.getString(7),rs.getString(8)));
						}
						tabart.setItems(dataArt);
					}catch(SQLException ex) {
						Logger.getLogger(ArticleController.class.getName()).log(Level.SEVERE, null,ex);
					}
				}
						
			}
			);
		}
		private void loadDataDBCom() {
			dataCom.clear();
			try {
				Connection conn = ConnectionDB.conDB();
				PreparedStatement pst=conn.prepareStatement("Select * from commande");
				ResultSet rs=pst.executeQuery();
				while(rs.next()) {
					dataCom.add(new Commande(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getInt(10),rs.getString(11)));
				}
			}
			catch(SQLException ex){
				Logger.getLogger(CommandeController.class.getName()).log(Level.SEVERE, null,ex);
			}
			tabcom.setItems(dataCom);
		}
		    
		private void searchCom() {
			rechercher.setOnKeyReleased(e->{
				if(rechercher.getText().equals("")) {
					loadDataDBCom();
				}
				else {
					dataCom.clear();
					String sql= "Select * from commande where id_commande LIKE '%"+rechercher.getText()+"%' " + "UNION Select * from commande where id_client LIKE '%"+rechercher.getText()+"%' "+ "UNION Select * from commande where Id_Article LIKE '%"+rechercher.getText()+"%' "+ "UNION Select * from commande where Nom_Client LIKE '%"+rechercher.getText()+"%' "+ "UNION Select * from commande where Prenom_Client LIKE '%"+rechercher.getText()+"%' "+ "UNION Select * from commande where Ref_Article LIKE '%"+rechercher.getText()+"%' ";
					try {
						Connection conn = ConnectionDB.conDB();
						PreparedStatement pst=conn.prepareStatement(sql);
						ResultSet rs=pst.executeQuery();
						while(rs.next()) {
							dataCom.add(new Commande(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getInt(10),rs.getString(11)));
						}
						tabcom.setItems(dataCom);
					}catch(SQLException ex) {
						Logger.getLogger(CommandeController.class.getName()).log(Level.SEVERE, null,ex);
					}
				}
						
			}
			);
		}
		
		 public static int insert(Commande cl)
		    {
		    	Connection conn = ConnectionDB.conDB();
		    	int rs = 0;
		    	try {
		    		
		    		String sql = "insert into commande (id_client , Id_Article , Date_Commande, Nom_Client , Prenom_Client , Tel_Client	,Ref_Article,	Prix_Article, Quantite , Details ) values(?,?,?,?,?,?,?,?,?,?)";
		    		PreparedStatement stm = conn.prepareStatement(sql);
		    		
		    		stm.setString(1, cl.getIdcli());
		    		stm.setString(2, cl.getIdarticle());
		    		stm.setString(3, cl.getDatecom());
		    		stm.setString(4, cl.getNomcli());
		    		stm.setString(5, cl.getPrenomcli());
		    		stm.setString(6, cl.getTelcli());
		    		stm.setString(7, cl.getRefarticle());
		    		stm.setString(8, cl.getPrix());
		    		stm.setInt(9, cl.getQuantite());
		    		stm.setString(10, cl.getDetails());
		    		
		    		
		    		
		    		 rs = stm.executeUpdate();
		    		
		    		
					
				} catch (Exception e) {
					// TODO: handle exception
					System.out.println(e.getMessage());
				}
		    	
		    return rs;	
		    }
		    public String Idrt() {
		    	 Commande selected =tabcom.getSelectionModel().getSelectedItem();
			        String idd = selected.getIdarticle();
			        System.out.println("id du article a modifier"+idd);
		    	return idd;
		    }
		    public int quantity() {
		    	 Article selected =tabart.getSelectionModel().getSelectedItem();
			        int quantity = selected.getQuantite();
			        System.out.println("quantity du article "+quantity);
		    	return quantity;
		    }
		
		@FXML
		public void ajouter(ActionEvent event) throws SQLException {
			// TODO Autogenerated
		
		LocalDate dateemp=LocalDate.now();
	      String IDCLIENT=idclient.getText();
	      String NOMCLIENT=nomclient.getText();
	      String PRENOMCLIENT=prenomclient.getText();
	      String TELEPHONECLIENT=telephoneclient.getText();
	      String IDARTICLE=idarticle.getText();
	      String REFARTICLE=refarticle.getText();
	      String PRIXARTICLE=prixarticle.getText();
	      String DETAILS=details.getText();
	      String DATE=dateemp.toString();
	      String QUANTITE=quanttarticle.getText();
	      int Quant=Integer.parseInt(QUANTITE);
	    if(quantity()<Quant) {
	    	lbl.setText("Quantité saisie dépasse la quantité d'article");
            Alert alert = new Alert (Alert.AlertType.ERROR);
            alert.setTitle("Quantité d'article");
            alert.setHeaderText("Information");
            alert.setContentText("Saisissez une quantité inférieure ou égale à "+quantity());
            alert.showAndWait();
	    }
	    else {
	    	lbl.setText("");
		 Commande dm = new Commande();
	      
	     
	      dm.setIdcli(IDCLIENT);
	      dm.setDatecom(DATE);
	      dm.setNomcli(NOMCLIENT);
	      dm.setPrenomcli(PRENOMCLIENT);
	      dm.setTelcli(TELEPHONECLIENT);
	      dm.setDetails(DETAILS);
	      dm.setIdarticle(IDARTICLE);
	      dm.setRefarticle(REFARTICLE);
	      dm.setPrix(PRIXARTICLE);
	      dm.setQuantite(Quant);

	      int status= insert(dm);
	      if(status>0){
	    	  
	    	  
	    	  
	    	  Article l=new Article();
	    	  l.setId(IDARTICLE);
	    	  Article li =tabart.getItems().get(tabart.getSelectionModel().getSelectedIndex());
	    	  int quantite= li.getQuantite();
	    	  l.setQuantite(quantite-Quant);
	    	  
	    	  String sql="UPDATE `article` SET Quantite=? WHERE Id_Article=? ";
	    	  Connection conn = ConnectionDB.conDB();
             PreparedStatement stat;
             stat=conn.prepareStatement(sql);
             stat.setInt(1, l.getQuantite());
             stat.setString(2, l.getId());
          
             
             stat.executeUpdate();
             conn.close();
	    	  
	          Alert alert = new Alert (AlertType.INFORMATION);
	          alert.setTitle("Ajouter Commande");
	          alert.setHeaderText("Information");
	          alert.setContentText("Commande ajoutée avec succès");
	          alert.showAndWait();
	      }else{
	          Alert alert = new Alert (AlertType.ERROR);
	          alert.setTitle("Ajouter Commande");
	          alert.setHeaderText("Information");
	          alert.setContentText("Ajout de commande échoué");
	          alert.showAndWait();
	          
	      }
	      viewCom();
			viewArt();
	    }
		}
		
		
		   public static int update(Commande cl,String idd)
			{
				Connection conn = ConnectionDB.conDB();
		    	int d = 0;
		    	try {
		    		
		    		String sql = "update commande set  id_client = ? , Id_Article= ?  , Date_Commande = ? , Nom_Client = ? , Prenom_Client = ? , Tel_Client	= ? , Ref_Article = ?  , Prix_Article =? , Quantite = ? , Details = ? where id_commande = ?  ";
		    		PreparedStatement stm = conn.prepareStatement(sql);
		    		
		    		stm.setString(1, cl.getIdcli());
		    		stm.setString(2, cl.getIdarticle());
		    		stm.setString(3, cl.getDatecom());
		    		stm.setString(4, cl.getNomcli());
		    		stm.setString(5, cl.getPrenomcli());
		    		stm.setString(6, cl.getTelcli());
		    		stm.setString(7, cl.getRefarticle());
		    		stm.setString(8, cl.getPrix());
		    		stm.setInt(9, cl.getQuantite());
		    		stm.setString(10, cl.getDetails());
		    		stm.setString(11, idd);
		    		
		    		 d = stm.executeUpdate();
		    		
		    		
					
				} catch (SQLException e) {
					// TODO: handle exception
					System.out.println(e.getMessage());
				}
		    	
		    return d;	
				
				
				
			}
			
		   public int qutt() throws SQLException {
			   
			   
			   Commande selected =tabcom.getSelectionModel().getSelectedItem();
		        int quantt = selected.getQuantite();
		        System.out.println("quantite du article a modifier"+quantt);
			   
	    		Connection conne = ConnectionDB.conDB();
	    		PreparedStatement ps = null;
	    		 ResultSet rs = null;
	    		int quttt=0;
	    		
	    		String sql3="SELECT Quantite from `article` WHERE Id_Article=?";
	    		
	    		 ps = conne.prepareStatement(sql3);
	             ps.setString(1, Idrt());
	          System.out.println("id"+Idrt());
	           
	             rs = ps.executeQuery();
	             if (rs.next()) {
	            	 
	            	 quttt =rs.getInt("Quantite")+quantt;
	                 
	            	 System.out.println("qutt"+quttt);
	            	 
	            	 
	            //	 a.setQuantite(qutt);
	            	 
	             }else {
	            	 System.out.println("erreur");
	             }
	             
	             return quttt;
		   }
		    
		    public void modifier (ActionEvent event) throws SQLException 
			{
		    	

				LocalDate dateemp=LocalDate.now();
			      String IDCLIENT=idclient.getText();
			      String NOMCLIENT=nomclient.getText();
			      String PRENOMCLIENT=prenomclient.getText();
			      String TELEPHONECLIENT=telephoneclient.getText();
			      String IDARTICLE=idarticle.getText();
			      String REFARTICLE=refarticle.getText();
			      String PRIXARTICLE=prixarticle.getText();
			      String DETAILS=details.getText();
			      String DATE=dateemp.toString();
			      String QUANTITE=quanttarticle.getText();
			      int Quant=Integer.parseInt(QUANTITE);
			     // String logid = LoginController.getlogid();
			      if(quantity()<Quant) {
				    	lbl.setText("Quantité saisie dépasse la quantité d'article");
			            Alert alert = new Alert (Alert.AlertType.ERROR);
			            alert.setTitle("Quantité d'article");
			            alert.setHeaderText("Information");
			            alert.setContentText("Saisissez une quantité inférieure ou égale à "+quantity());
			            alert.showAndWait();
				    }
				    else {
				    	lbl.setText("");
			      
			      Commande dm = new Commande();
			      
			     
			      dm.setIdcli(IDCLIENT);
			      dm.setDatecom(DATE);
			      dm.setNomcli(NOMCLIENT);
			      dm.setPrenomcli(PRENOMCLIENT);
			      dm.setTelcli(TELEPHONECLIENT);
			      dm.setDetails(DETAILS);
			      dm.setIdarticle(IDARTICLE);
			      dm.setRefarticle(REFARTICLE);
			      dm.setPrix(PRIXARTICLE);
			      dm.setQuantite(Quant);
		    	
		    	
		    	 Commande selected =tabcom.getSelectionModel().getSelectedItem();
			        String idd = selected.getId();
			        System.out.println("idd"+idd);
		    	int etat = update(dm,idd);
		    	
		    	
		    	if (etat > 0) {
		    
		    		
		    		Article a=new Article();
		             int QUTT=qutt();
		             String ID=Idrt();
		             a.setQuantite(QUTT);
		             a.setId(ID);
		    		
		    		String sql1="UPDATE `article` SET Quantite=? WHERE Id_Article=? ";
		    		Connection con = ConnectionDB.conDB();
		              PreparedStatement st;
		              st=con.prepareStatement(sql1);
		              st.setInt(1, a.getQuantite());
		              st.setString(2, a.getId());
		           
		              
		              st.executeUpdate();
		              con.close();
			    	  
		    		
		
		      	  Article l=new Article();
		    	  l.setId(IDARTICLE);
		    	  Article li =tabart.getItems().get(tabart.getSelectionModel().getSelectedIndex());
		    	  int quantite= li.getQuantite();
		    	  l.setQuantite(quantite-Quant);
		    	  
		    	  String sql="UPDATE `article` SET Quantite=? WHERE Id_Article=? ";
		    	  Connection conn = ConnectionDB.conDB();
	              PreparedStatement stat;
	              stat=conn.prepareStatement(sql);
	              stat.setInt(1, l.getQuantite());
	              stat.setString(2, l.getId());
	           
	              
	              stat.executeUpdate();
	              conn.close();
		    	  
		    	
		    	Alert alert = new Alert(AlertType.INFORMATION);
		    	alert.setTitle("Modifier Commande");
		    	alert.setHeaderText("Information");
		    	alert.setContentText("Commande bien Modifiée");
		    	alert.showAndWait();
		    	
		              }
		    	else
		    	{
		    		Alert alert = new Alert(AlertType.ERROR);
			    	alert.setTitle("Modifier Commande");
			    	alert.setHeaderText("Information");
			    	alert.setContentText("Commande Non Modifiée");
			    	alert.showAndWait();	
		    
		    	}
		    	
		    	  viewCom();
					viewArt();
				    }
			}
		    public static int supp(String id)
			{
				Connection conn = ConnectionDB.conDB();
				int d = 0;
				
				
				try {
					
					String sql = "delete from commande where id_commande = ? ";
					PreparedStatement stm = conn.prepareStatement(sql);
					stm.setString(1, id);
					d = stm.executeUpdate();
					
				} catch (SQLException e) {
					// TODO: handle exception
					
					System.out.println(e.getMessage());
				}
				
				
				
				return d;
			
				
			}
		    
		    
		    public void delete (ActionEvent event)
			{
		    	Commande selected =tabcom.getSelectionModel().getSelectedItem();
		        String idd = selected.getId();
		        tabcom.getItems().removeAll(selected);
				int etat = supp(idd);
				
				if(etat > 0) 
		        {
		    	
		    	Alert alert = new Alert(AlertType.INFORMATION);
		    	alert.setTitle("Supprimer Commande");
		    	alert.setHeaderText("Information");
		    	alert.setContentText("Commande bien Supprimée");
		    	alert.showAndWait();
		    	
		              }
		    	else
		    	{
		    		Alert alert = new Alert(AlertType.ERROR);
			    	alert.setTitle("Supprimer Commande");
			    	alert.setHeaderText("Information");
			    	alert.setContentText("Commande Non Supprimée");
			    	alert.showAndWait();	
		    
		    	}
				
				
			}
		    
}
