package com_commande;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.ComboBox;
import projet.bin.Commande;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDate;

import com_connection.ConnectionDB;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.Alert;
import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class CommandeController {
	@FXML
    private ComboBox<String> idbox;
	@FXML
	private TextField txtnom;
	@FXML
	private TextField txtprenom;
	@FXML
	private TextField txttel;
	@FXML
	private TextField txtdet;
	@FXML
	private DatePicker txtdate;
	@FXML
	private Label exit;
	@FXML
	private TableView<Commande> tab;
	@FXML
	private TableColumn<Commande, String> col_id;
	@FXML
	private TableColumn<Commande, String> col_idcli;
	@FXML
	private TableColumn<Commande, String> col_date;
	@FXML
	private TableColumn<Commande, String> col_nom;
	@FXML
	private TableColumn<Commande, String> col_prenom;
	@FXML
	private TableColumn<Commande, String> col_tel;
	@FXML
	private TableColumn<Commande, String> col_det;
	@FXML
	private TextField searchfield;
    static String tt;


	// Event Listener on Button.onAction
	@FXML
	public void Modifier(ActionEvent event) {
		// TODO Autogenerated
		Connection con= ConnectionDB.conDB();
    	PreparedStatement st = null;
    	Commande a = new Commande();
    	String numcli = idbox.getValue() ; 
    	 tt = idbox.getValue() ; 
    	
    	String nom = txtprenom.getText();
    	String prenom = txtnom.getText();
    	LocalDate datec = txtdate.getValue();
    	String datecom=datec.toString();
    	String tel = txttel.getText();
    	String det = txtdet.getText();
    	a.setIdcli(numcli);
    	a.setNomcli(nom);
    	a.setPrenomcli(prenom);
    	a.setDatecom(datecom);
    	a.setTelcli(tel);
    	a.setDetails(det);
    	String rqt ="Update  commande set  id_commande =? , id_client=? ,date_commande=?,nom_client=?,prenom_client=?,tel_client=?,details = ?  ";
    	try {
			st = con.prepareStatement(rqt);
			st.setString(1, a.getId());
			st.setString(2, a.getIdcli());
			st.setString(3, a.getDatecom());
			st.setString(4, a.getNomcli());
			st.setString(5, a.getPrenomcli());
			st.setString(6, a.getTelcli());
			st.setString(7, a.getDetails());
			st.executeUpdate();
			con.close();
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("C'est fait");
			alert.setHeaderText(null);
			alert.setContentText("Commande bien Modifié");
			alert.showAndWait();			
			//Update();
		//	search();
			//FillCombotype();
		//	FillComboInd();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			Alert alert = new Alert(AlertType.WARNING);
			alert.setTitle("ERREUR");
		alert.setHeaderText(null);
			alert.setContentText("Commande n'a pas été Modifiée");
			System.out.println(e.getMessage()); 
			alert.showAndWait();
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void Supprimer(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	
	
	
	 public static  String sendIdCli() {
	     	String a=tt;
	     	return(a);
	     }
	    
	
	
	
	
	//----------------------------------------------AJOUTER----------------------------------------------//
	
	@FXML
	public void Ajouter(ActionEvent event) {
		// TODO Autogenerated
		Connection con= ConnectionDB.conDB();
    	PreparedStatement st = null;
    	Commande a = new Commande();
    	String numcli = idbox.getValue() ; 
    	 tt = idbox.getValue() ; 
    	
    //	String nom = com_connection.ConnectionDB.getNom();
    	//String prenom = com_connection.ConnectionDB.getPrenom();
    	//txtnom.setText(nom);
    	//txtprenom.setText(prenom);
    	LocalDate datec = txtdate.getValue();
    	String datecom=datec.toString();
    	String tel = txttel.getText();
    	String det = txtdet.getText();
    	a.setIdcli(numcli);
    	//a.setNomcli(nom);
    	//a.setPrenomcli(prenom);
    	a.setDatecom(datecom);
    	a.setTelcli(tel);
    	a.setDetails(det);
    	String rqt ="Insert into commande ( id_commande, id_client	 ,Date_Commande,Nom_Client,Prenom_Client,Tel_Client, Details )  values(?,?,?,?,?,?,?) ";;
    	try {
			st = con.prepareStatement(rqt);
			st.setString(1, a.getId());
			st.setString(2, a.getIdcli());
			st.setString(3, a.getDatecom());
			st.setString(4, a.getNomcli());
			st.setString(5, a.getPrenomcli());
			st.setString(6, a.getTelcli());
			st.setString(7, a.getDetails());
			st.executeUpdate();
			con.close();
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("C'est fait");
			alert.setHeaderText(null);
			alert.setContentText("Commande bien ajoutée");
			alert.showAndWait();			
			//Update();
		//	search();
			//FillCombotype();
		//	FillComboInd();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			Alert alert = new Alert(AlertType.WARNING);
			alert.setTitle("ERREUR");
		alert.setHeaderText(null);
			alert.setContentText("Commande n'a pas été ajoutée");
			System.out.println(e.getMessage()); 
			alert.showAndWait();
		}
	}
	
	
	
	
	
	
	
	
	
	
	
	// Event Listener on TextField[#searchfield].onAction
	@FXML
	public void search(ActionEvent event) {
		// TODO Autogenerated
	}
}
