package admin;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

public class AdminController {
	@FXML
	private Label exit;
	double xOffset, yOffset;
	@FXML
    private void handleButtonAction(MouseEvent event) {
       
            System.exit(0);////
       
	}
	
       
		@FXML
		public void signout(MouseEvent event) throws IOException {
			// TODO Autogenerated
			Parent homePage = FXMLLoader.load(getClass().getResource("/application/Login.fxml"));
	        Scene homepageScene = new Scene(homePage);
	        Stage appStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        appStage.setScene(homepageScene);
	        homepageScene.setFill(Color.TRANSPARENT);
	        appStage.show();
		
	}
	@FXML
    private void compte(ActionEvent event) throws IOException {
       

		   Stage stage1 = new Stage();


        Scene scene;
		
			scene = new Scene(FXMLLoader.load(getClass().getResource("/com_adminsettings/AdminSettings.fxml")));
		
<<<<<<< HEAD
			 stage1.setScene(scene);
		        stage1.initStyle(StageStyle.TRANSPARENT);
		        scene.setFill(Color.TRANSPARENT);
		        stage1.show();
=======
        stage.setScene(scene);
       // stage.initStyle(StageStyle.TRANSPARENT);
        scene.setFill(Color.TRANSPARENT);
       
       stage.show();
       scene.setOnMousePressed(new EventHandler<MouseEvent>() {
			@Override
			public void handle(MouseEvent event) {
				xOffset = event.getSceneX();
				yOffset = event.getSceneY();
			}
		});
		scene.setOnMouseDragged(new EventHandler<MouseEvent>() {
			@Override
			public void handle(MouseEvent event) {
				stage.setX(event.getScreenX() - xOffset);
				stage.setY(event.getScreenY() - yOffset);
			}
		});
>>>>>>> branch 'master' of https://github.com/THEDEATHSQUAD/Gestionstock.git
        
	}
	@FXML
    private void vendeurs(ActionEvent event) throws IOException  {
       
		   Stage stage1 = new Stage();


            Scene scene;
			
				scene = new Scene(FXMLLoader.load(getClass().getResource("/comvendeur/VenDeur.fxml")));
			
<<<<<<< HEAD
				 stage1.setScene(scene);
			        stage1.initStyle(StageStyle.TRANSPARENT);
			        scene.setFill(Color.TRANSPARENT);
			        stage1.show();
=======
            stage.setScene(scene);
           // stage.initStyle(StageStyle.TRANSPARENT);
            scene.setFill(Color.TRANSPARENT);
           
           stage.show();
           scene.setOnMousePressed(new EventHandler<MouseEvent>() {
				@Override
				public void handle(MouseEvent event) {
					xOffset = event.getSceneX();
					yOffset = event.getSceneY();
				}
			});
			scene.setOnMouseDragged(new EventHandler<MouseEvent>() {
				@Override
				public void handle(MouseEvent event) {
					stage.setX(event.getScreenX() - xOffset);
					stage.setY(event.getScreenY() - yOffset);
				}
			});
>>>>>>> branch 'master' of https://github.com/THEDEATHSQUAD/Gestionstock.git
	}

}
